In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
train = pd.read_csv('employee_train.csv')
test = pd.read_csv('employee_test.csv')

In [3]:
pd.options.display.max_columns = None

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   S.No                       1048 non-null   int64 
 1   Timestamp                  1048 non-null   object
 2   Age                        1048 non-null   int64 
 3   Gender                     1048 non-null   object
 4   Country                    1048 non-null   object
 5   state                      636 non-null    object
 6   self_employed              1030 non-null   object
 7   family_history             1048 non-null   object
 8   treatment                  1048 non-null   object
 9   work_interfere             812 non-null    object
 10  no_employees               1048 non-null   object
 11  remote_work                1048 non-null   object
 12  tech_company               1048 non-null   object
 13  benefits                   1035 non-null   object
 14  care_opt

In [5]:
train.shape

(1048, 28)

In [6]:
test.shape

(210, 27)

In [7]:
train.describe()

S.No           Age
count  1048.000000  1.048000e+03
mean    524.500000  9.541988e+07
std     302.675844  3.089010e+09
min       1.000000 -1.726000e+03
25%     262.750000  2.700000e+01
50%     524.500000  3.100000e+01
75%     786.250000  3.600000e+01
max    1048.000000  1.000000e+11

In [8]:
train.describe(include = 'object')

Timestamp Gender        Country state self_employed  \
count              1048   1048           1048   636          1030   
unique              679     45             42    45             2   
top     8/27/2014 15:24   Male  United States    CA            No   
freq                  8    518            644   123           906   

       family_history treatment work_interfere no_employees remote_work  \
count            1048      1048            812         1048        1048   
unique              2         2              4            6           2   
top                No        No      Sometimes       25-Jun          No   
freq              643       536            386          245         733   

       tech_company benefits care_options wellness_program seek_help  \
count          1048     1035         1048             1044      1048   
unique            2        3            3                3         3   
top             Yes      Yes           No               No        No   
freq            870      400          422              692       534   

         anonymity       leave mental_health_consequence  \
count         1048        1044                      1048   
unique           3           5                         3   
top     Don't know  Don't know                        No   
freq           685         462                       424   

       phys_health_consequence     coworkers supervisor  \
count                     1048          1048       1048   
unique                       3             3          3   
top                         No  Some of them        Yes   
freq                       773           651        439   

       mental_health_interview phys_health_interview mental_vs_physical  \
count                     1048                  1048               1048   
unique                       3                     3                  3   
top                         No                 Maybe         Don't know   
freq                       835                   461                471   

       obs_consequence                         comments  
count             1048                              132  
unique               2                              128  
top                 No  * Small family business - YMMV.  
freq               902                                5

In [9]:
train[train.Age == train.Age.max()]

S.No        Timestamp          Age Gender   Country state self_employed  \
390   391  8/27/2014 15:24  99999999999    All  Zimbabwe   NaN           Yes   

    family_history treatment work_interfere no_employees remote_work  \
390            Yes       Yes          Often        5-Jan          No   

    tech_company benefits care_options wellness_program seek_help anonymity  \
390          Yes       No          Yes               No        No        No   

              leave mental_health_consequence phys_health_consequence  \
390  Very difficult                       Yes                     Yes   

    coworkers supervisor mental_health_interview phys_health_interview  \
390        No         No                     Yes                    No   

    mental_vs_physical obs_consequence comments  
390                 No             Yes      NaN

In [10]:
for i in train:
    print(i)
    print(train[i].value_counts())
    print(train[i].value_counts(normalize = True) * 100)
    print(train[i].unique())
    print(train[i].nunique())
    print(train.groupby(i)['treatment'].value_counts(normalize = True)*100) 
    print('--'* 30)

S.No
S.No
1       1
689     1
691     1
692     1
693     1
       ..
355     1
356     1
357     1
358     1
1048    1
Name: count, Length: 1048, dtype: int64
S.No
1       0.09542
689     0.09542
691     0.09542
692     0.09542
693     0.09542
         ...   
355     0.09542
356     0.09542
357     0.09542
358     0.09542
1048    0.09542
Name: proportion, Length: 1048, dtype: float64
[   1    2    3 ... 1046 1047 1048]
1048
S.No  treatment
1     Yes          100.0
2     No           100.0
3     No           100.0
4     Yes          100.0
5     No           100.0
                   ...  
1044  Yes          100.0
1045  Yes          100.0
1046  Yes          100.0
1047  Yes          100.0
1048  No           100.0
Name: proportion, Length: 1048, dtype: float64
------------------------------------------------------------
Timestamp
Timestamp
8/27/2014 15:24    8
8/27/2014 12:31    8
8/27/2014 15:23    8
8/27/2014 11:43    7
8/27/2014 15:31    6
                  ..
8/27/2014 22:55    1
8/27/

In [11]:
train.columns

Index(['S.No', 'Timestamp', 'Age', 'Gender', 'Country', 'state',
       'self_employed', 'family_history', 'treatment', 'work_interfere',
       'no_employees', 'remote_work', 'tech_company', 'benefits',
       'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [12]:
train.columns

Index(['S.No', 'Timestamp', 'Age', 'Gender', 'Country', 'state',
       'self_employed', 'family_history', 'treatment', 'work_interfere',
       'no_employees', 'remote_work', 'tech_company', 'benefits',
       'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [13]:
train.drop(columns = 'S.No',inplace=True)

In [14]:
train.drop(columns = 'Timestamp',inplace=True)

In [15]:
train.drop(columns = 'Gender',inplace=True)

In [16]:
train.drop(columns = 'Country',inplace=True)

In [17]:
train.drop(columns = 'state',inplace=True)

In [18]:
train.drop(columns = 'self_employed',inplace=True)

In [19]:
train.drop(columns = 'remote_work',inplace=True)

In [20]:
train.drop(columns = 'tech_company',inplace=True)

In [21]:
train.drop(columns = 'coworkers',inplace=True)

In [22]:
train.drop(columns = 'mental_health_interview',inplace=True)

In [23]:
train.drop(columns = 'phys_health_interview',inplace=True)

In [24]:
train.drop(columns = 'mental_vs_physical',inplace=True)

In [25]:
train.drop(columns = 'obs_consequence',inplace=True)

In [26]:
train.drop(columns = 'comments',inplace=True)

In [27]:
train

Age family_history treatment work_interfere    no_employees    benefits  \
0      37             No       Yes          Often          25-Jun         Yes   
1      44             No        No         Rarely  More than 1000  Don't know   
2      32             No        No         Rarely          25-Jun          No   
3      31            Yes       Yes          Often          26-100          No   
4      31             No        No          Never         100-500         Yes   
...   ...            ...       ...            ...             ...         ...   
1043   26             No       Yes      Sometimes          25-Jun         Yes   
1044   29             No       Yes          Often  More than 1000         Yes   
1045   26            Yes       Yes      Sometimes         100-500         Yes   
1046   33            Yes       Yes      Sometimes          25-Jun          No   
1047   28            Yes        No      Sometimes         100-500          No   

     care_options wellness_program   seek_help   anonymity  \
0        Not sure               No         Yes         Yes   
1              No       Don't know  Don't know  Don't know   
2              No               No          No  Don't know   
3             Yes               No          No          No   
4              No       Don't know  Don't know  Don't know   
...           ...              ...         ...         ...   
1043          Yes               No          No         Yes   
1044          Yes               No          No  Don't know   
1045     Not sure               No          No         Yes   
1046     Not sure               No          No  Don't know   
1047           No               No          No  Don't know   

                   leave mental_health_consequence phys_health_consequence  \
0          Somewhat easy                        No                      No   
1             Don't know                     Maybe                      No   
2     Somewhat difficult                        No                      No   
3     Somewhat difficult                       Yes                     Yes   
4             Don't know                        No                      No   
...                  ...                       ...                     ...   
1043          Don't know                     Maybe                      No   
1044          Don't know                     Maybe                      No   
1045          Don't know                     Maybe                      No   
1046       Somewhat easy                        No                      No   
1047       Somewhat easy                        No                      No   

        supervisor  
0              Yes  
1               No  
2              Yes  
3               No  
4              Yes  
...            ...  
1043            No  
1044            No  
1045            No  
1046           Yes  
1047  Some of them  

[1048 rows x 14 columns]

In [28]:
train.columns

Index(['Age', 'family_history', 'treatment', 'work_interfere', 'no_employees',
       'benefits', 'care_options', 'wellness_program', 'seek_help',
       'anonymity', 'leave', 'mental_health_consequence',
       'phys_health_consequence', 'supervisor'],
      dtype='object')

In [29]:
train.work_interfere.replace({'Rarely':'Often','Sometimes':'Often'},inplace = True)

In [30]:
train.wellness_program.replace({"Don't know":'No'},inplace = True)

In [31]:
train.seek_help.replace({"Don't know":'No'},inplace = True)

In [32]:
train.leave.replace({'Somewhat easy':'Easy_Approval',"Don't know":'Easy_Approval','Very easy':'Easy_Approval','Somewhat difficult': 'Difficult_Approval','Very difficult':'Difficult_Approval'},inplace = True)

In [33]:
train.mental_health_consequence.replace({'Maybe':'Yes'},inplace = True)

In [34]:
train.phys_health_consequence .replace({'Maybe':'Yes'},inplace = True)

In [35]:
train.care_options .replace({'Not sure':'No'},inplace = True)

In [36]:
cat_cols = train.select_dtypes(include=['object']).columns

In [37]:
cat_cols

Index(['family_history', 'treatment', 'work_interfere', 'no_employees',
       'benefits', 'care_options', 'wellness_program', 'seek_help',
       'anonymity', 'leave', 'mental_health_consequence',
       'phys_health_consequence', 'supervisor'],
      dtype='object')

In [38]:
for i in cat_cols:
    print(train[i].value_counts())
    print(train[i].value_counts(normalize = True) * 100)
    print(train[i].unique())
    print(train[i].nunique())
    print(train.groupby(i)['treatment'].value_counts(normalize = True)*100) 
    print('--'* 30)

family_history
No     643
Yes    405
Name: count, dtype: int64
family_history
No     61.354962
Yes    38.645038
Name: proportion, dtype: float64
['No' 'Yes']
2
family_history  treatment
No              No           66.407465
                Yes          33.592535
Yes             Yes          73.086420
                No           26.913580
Name: proportion, dtype: float64
------------------------------------------------------------
treatment
No     536
Yes    512
Name: count, dtype: int64
treatment
No     51.145038
Yes    48.854962
Name: proportion, dtype: float64
['Yes' 'No']
2
treatment
No     100.0
Yes    100.0
Name: proportion, dtype: float64
------------------------------------------------------------
work_interfere
Often    634
Never    178
Name: count, dtype: int64
work_interfere
Often    78.078818
Never    21.921182
Name: proportion, dtype: float64
['Often' 'Never' nan]
2
work_interfere  treatment
Never           No           85.955056
                Yes          14.044944
Oft

In [39]:
train.isnull().sum()

Age                            0
family_history                 0
treatment                      0
work_interfere               236
no_employees                   0
benefits                      13
care_options                   0
wellness_program               4
seek_help                      0
anonymity                      0
leave                          4
mental_health_consequence      0
phys_health_consequence        0
supervisor                     0
dtype: int64

In [40]:
train.work_interfere.unique()

array(['Often', 'Never', nan], dtype=object)

In [41]:
train.work_interfere.fillna("Never",inplace=True)

In [42]:
train.benefits.unique()

array(['Yes', "Don't know", 'No', nan], dtype=object)

In [43]:
train.benefits.fillna("Don't know",inplace=True)

In [44]:
train.wellness_program.unique()

array(['No', 'Yes', nan], dtype=object)

In [45]:
train.wellness_program.fillna("No",inplace=True)

In [46]:
train.leave.unique()

array(['Easy_Approval', 'Difficult_Approval', nan], dtype=object)

In [47]:
train.leave.fillna("Easy_Approval",inplace=True)

In [48]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Age                        1048 non-null   int64 
 1   family_history             1048 non-null   object
 2   treatment                  1048 non-null   object
 3   work_interfere             1048 non-null   object
 4   no_employees               1048 non-null   object
 5   benefits                   1048 non-null   object
 6   care_options               1048 non-null   object
 7   wellness_program           1048 non-null   object
 8   seek_help                  1048 non-null   object
 9   anonymity                  1048 non-null   object
 10  leave                      1048 non-null   object
 11  mental_health_consequence  1048 non-null   object
 12  phys_health_consequence    1048 non-null   object
 13  supervisor                 1048 non-null   object
dtypes: int64

In [49]:
train.treatment.unique()

array(['Yes', 'No'], dtype=object)

In [50]:
train.treatment

0       Yes
1        No
2        No
3       Yes
4        No
       ... 
1043    Yes
1044    Yes
1045    Yes
1046    Yes
1047     No
Name: treatment, Length: 1048, dtype: object

In [51]:
train

Age family_history treatment work_interfere    no_employees    benefits  \
0      37             No       Yes          Often          25-Jun         Yes   
1      44             No        No          Often  More than 1000  Don't know   
2      32             No        No          Often          25-Jun          No   
3      31            Yes       Yes          Often          26-100          No   
4      31             No        No          Never         100-500         Yes   
...   ...            ...       ...            ...             ...         ...   
1043   26             No       Yes          Often          25-Jun         Yes   
1044   29             No       Yes          Often  More than 1000         Yes   
1045   26            Yes       Yes          Often         100-500         Yes   
1046   33            Yes       Yes          Often          25-Jun          No   
1047   28            Yes        No          Often         100-500          No   

     care_options wellness_program seek_help   anonymity               leave  \
0              No               No       Yes         Yes       Easy_Approval   
1              No               No        No  Don't know       Easy_Approval   
2              No               No        No  Don't know  Difficult_Approval   
3             Yes               No        No          No  Difficult_Approval   
4              No               No        No  Don't know       Easy_Approval   
...           ...              ...       ...         ...                 ...   
1043          Yes               No        No         Yes       Easy_Approval   
1044          Yes               No        No  Don't know       Easy_Approval   
1045           No               No        No         Yes       Easy_Approval   
1046           No               No        No  Don't know       Easy_Approval   
1047           No               No        No  Don't know       Easy_Approval   

     mental_health_consequence phys_health_consequence    supervisor  
0                           No                      No           Yes  
1                          Yes                      No            No  
2                           No                      No           Yes  
3                          Yes                     Yes            No  
4                           No                      No           Yes  
...                        ...                     ...           ...  
1043                       Yes                      No            No  
1044                       Yes                      No            No  
1045                       Yes                      No            No  
1046                        No                      No           Yes  
1047                        No                      No  Some of them  

[1048 rows x 14 columns]

In [52]:
train.treatment = train.treatment.map({'Yes':1,'No':0})

In [53]:
train[train.duplicated()].shape

(26, 14)

In [54]:
train.drop_duplicates(inplace=True)

In [55]:
ftrain = pd.get_dummies(train,drop_first = True).astype('int')

In [56]:
ftrain

Age  treatment  family_history_Yes  work_interfere_Often  \
0      37          1                   0                     1   
1      44          0                   0                     1   
2      32          0                   0                     1   
3      31          1                   1                     1   
4      31          0                   0                     0   
...   ...        ...                 ...                   ...   
1043   26          1                   0                     1   
1044   29          1                   0                     1   
1045   26          1                   1                     1   
1046   33          1                   1                     1   
1047   28          0                   1                     1   

      no_employees_25-Jun  no_employees_26-100  no_employees_5-Jan  \
0                       1                    0                   0   
1                       0                    0                   0   
2                       1                    0                   0   
3                       0                    1                   0   
4                       0                    0                   0   
...                   ...                  ...                 ...   
1043                    1                    0                   0   
1044                    0                    0                   0   
1045                    0                    0                   0   
1046                    1                    0                   0   
1047                    0                    0                   0   

      no_employees_500-1000  no_employees_More than 1000  benefits_No  \
0                         0                            0            0   
1                         0                            1            0   
2                         0                            0            1   
3                         0                            0            1   
4                         0                            0            0   
...                     ...                          ...          ...   
1043                      0                            0            0   
1044                      0                            1            0   
1045                      0                            0            0   
1046                      0                            0            1   
1047                      0                            0            1   

      benefits_Yes  care_options_Yes  wellness_program_Yes  seek_help_Yes  \
0                1                 0                     0              1   
1                0                 0                     0              0   
2                0                 0                     0              0   
3                0                 1                     0              0   
4                1                 0                     0              0   
...            ...               ...                   ...            ...   
1043             1                 1                     0              0   
1044             1                 1                     0              0   
1045             1                 0                     0              0   
1046             0                 0                     0              0   
1047             0                 0                     0              0   

      anonymity_No  anonymity_Yes  leave_Easy_Approval  \
0                0              1                    1   
1                0              0                    1   
2                0              0                    0   
3                1              0                    0   
4                0              0                    1   
...            ...            ...                  ...   
1043             0              1                    1   
1044             0              0                    1   
1045             0              1               

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X = ftrain.drop(columns = 'treatment',axis=1)
y = ftrain['treatment']

In [59]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix,classification_report

In [61]:
model1 = LogisticRegression()
model1.fit(X_train,y_train)
y_train_pred = model1.predict(X_train)
y_test_pred = model1.predict(X_test)
display(confusion_matrix(y_train,y_train_pred))
display(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_train,y_train_pred))
print(classification_report(y_test,y_test_pred))

array([[329,  94],
       [ 41, 353]], dtype=int64)

array([[75, 20],
       [22, 88]], dtype=int64)

              precision    recall  f1-score   support

           0       0.89      0.78      0.83       423
           1       0.79      0.90      0.84       394

    accuracy                           0.83       817
   macro avg       0.84      0.84      0.83       817
weighted avg       0.84      0.83      0.83       817

              precision    recall  f1-score   support

           0       0.77      0.79      0.78        95
           1       0.81      0.80      0.81       110

    accuracy                           0.80       205
   macro avg       0.79      0.79      0.79       205
weighted avg       0.80      0.80      0.80       205



In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Define the model
model = LogisticRegression()

# Define the hyperparameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],  # Regularization strength
    'penalty': ['l1', 'l2', 'elasticnet', None],  # Regularization type
    'solver': ['liblinear', 'saga']  # Compatible solvers
}

# Perform Grid Search with cross-validation
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predictions
y_train_pred = best_model.predict(X_train)
y_test_pred = best_model.predict(X_test)

# Model evaluation
print("Best Parameters:", grid_search.best_params_)
display(confusion_matrix(y_train, y_train_pred))
display(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_train, y_train_pred))
print(classification_report(y_test, y_test_pred))


Best Parameters: {'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}


array([[313, 110],
       [ 33, 361]], dtype=int64)

array([[72, 23],
       [14, 96]], dtype=int64)

              precision    recall  f1-score   support

           0       0.90      0.74      0.81       423
           1       0.77      0.92      0.83       394

    accuracy                           0.82       817
   macro avg       0.84      0.83      0.82       817
weighted avg       0.84      0.82      0.82       817

              precision    recall  f1-score   support

           0       0.84      0.76      0.80        95
           1       0.81      0.87      0.84       110

    accuracy                           0.82       205
   macro avg       0.82      0.82      0.82       205
weighted avg       0.82      0.82      0.82       205



In [63]:
model2 = DecisionTreeClassifier()
model2.fit(X_train,y_train)
y_train_pred2 = model2.predict(X_train)
y_test_pred2 = model2.predict(X_test)
display(confusion_matrix(y_train,y_train_pred2))
display(confusion_matrix(y_test,y_test_pred2))
print(classification_report(y_train,y_train_pred2))
print(classification_report(y_test,y_test_pred2))

array([[423,   0],
       [  1, 393]], dtype=int64)

array([[73, 22],
       [36, 74]], dtype=int64)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       423
           1       1.00      1.00      1.00       394

    accuracy                           1.00       817
   macro avg       1.00      1.00      1.00       817
weighted avg       1.00      1.00      1.00       817

              precision    recall  f1-score   support

           0       0.67      0.77      0.72        95
           1       0.77      0.67      0.72       110

    accuracy                           0.72       205
   macro avg       0.72      0.72      0.72       205
weighted avg       0.72      0.72      0.72       205



In [64]:
model3 = RandomForestClassifier()
model3.fit(X_train,y_train)
y_train_pred3 = model3.predict(X_train)
y_test_pred3 = model3.predict(X_test)
display(confusion_matrix(y_train,y_train_pred3))
display(confusion_matrix(y_test,y_test_pred3))
print(classification_report(y_train,y_train_pred3))
print(classification_report(y_test,y_test_pred3))

array([[423,   0],
       [  1, 393]], dtype=int64)

array([[75, 20],
       [26, 84]], dtype=int64)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       423
           1       1.00      1.00      1.00       394

    accuracy                           1.00       817
   macro avg       1.00      1.00      1.00       817
weighted avg       1.00      1.00      1.00       817

              precision    recall  f1-score   support

           0       0.74      0.79      0.77        95
           1       0.81      0.76      0.79       110

    accuracy                           0.78       205
   macro avg       0.78      0.78      0.78       205
weighted avg       0.78      0.78      0.78       205



In [65]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Define parameter grid
param_grid = { 
    'max_depth': [None, 10, 20, 30], 
    'min_samples_split': [2, 5, 10], 
    'min_samples_leaf': [1, 2, 4]
}

# Initialize base model
rf = RandomForestClassifier(random_state=42)

# Perform Grid Search with Cross Validation
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, 
                           cv=5, n_jobs=-1, verbose=2, scoring='accuracy')

# Fit GridSearchCV on training data
grid_search.fit(X_train, y_train)

# Best parameters from GridSearchCV
print("Best Parameters:", grid_search.best_params_)

# Train model with best parameters
best_rf = grid_search.best_estimator_

# Predictions
y_train_pred = best_rf.predict(X_train)
y_test_pred = best_rf.predict(X_test)

# Evaluation
print("\nTrain Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))
print("\nTest Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

print("\nTrain Classification Report:")
print(classification_report(y_train, y_train_pred))
print("\nTest Classification Report:")
print(classification_report(y_test, y_test_pred))


Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Parameters: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5}

Train Confusion Matrix:
[[375  48]
 [ 26 368]]

Test Confusion Matrix:
[[78 17]
 [22 88]]

Train Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       423
           1       0.88      0.93      0.91       394

    accuracy                           0.91       817
   macro avg       0.91      0.91      0.91       817
weighted avg       0.91      0.91      0.91       817


Test Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.82      0.80        95
           1       0.84      0.80      0.82       110

    accuracy                           0.81       205
   macro avg       0.81      0.81      0.81       205
weighted avg       0.81      0.81      0.81       205



In [66]:
m3 = RandomForestClassifier(max_depth=4,min_samples_leaf=2,min_samples_split=5,random_state=42)  #for max_depth = 10 --- 90 and 84
m3.fit(X_train,y_train)
y_train_pred3 = m3.predict(X_train)
y_test_pred3 = m3.predict(X_test)
display(confusion_matrix(y_train,y_train_pred3))
display(confusion_matrix(y_test,y_test_pred3))
print(classification_report(y_train,y_train_pred3))
print(classification_report(y_test,y_test_pred3))

array([[346,  77],
       [ 45, 349]], dtype=int64)

array([[76, 19],
       [22, 88]], dtype=int64)

              precision    recall  f1-score   support

           0       0.88      0.82      0.85       423
           1       0.82      0.89      0.85       394

    accuracy                           0.85       817
   macro avg       0.85      0.85      0.85       817
weighted avg       0.85      0.85      0.85       817

              precision    recall  f1-score   support

           0       0.78      0.80      0.79        95
           1       0.82      0.80      0.81       110

    accuracy                           0.80       205
   macro avg       0.80      0.80      0.80       205
weighted avg       0.80      0.80      0.80       205



In [67]:
from sklearn.ensemble import AdaBoostClassifier

model4= AdaBoostClassifier()
model4.fit(X_train,y_train)
y_train_pred=model4.predict(X_train)
y_test_pred=model4.predict(X_test)
print(confusion_matrix(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_train,y_train_pred))
print(classification_report(y_test,y_test_pred))

[[330  93]
 [ 45 349]]
[[75 20]
 [22 88]]
              precision    recall  f1-score   support

           0       0.88      0.78      0.83       423
           1       0.79      0.89      0.83       394

    accuracy                           0.83       817
   macro avg       0.83      0.83      0.83       817
weighted avg       0.84      0.83      0.83       817

              precision    recall  f1-score   support

           0       0.77      0.79      0.78        95
           1       0.81      0.80      0.81       110

    accuracy                           0.80       205
   macro avg       0.79      0.79      0.79       205
weighted avg       0.80      0.80      0.80       205



In [68]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Define the AdaBoost classifier
model4 = AdaBoostClassifier()

# Define the hyperparameters for tuning
param_grid = {
    'n_estimators': [50, 100, 200],  # Number of weak learners
    'learning_rate': [0.01, 0.1, 1.0],  # Step size at each iteration
    'algorithm': ['SAMME', 'SAMME.R']  # Different boosting algorithms
}

# Perform Grid Search with cross-validation
grid_search = GridSearchCV(model4, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best parameters
print("Best parameters:", grid_search.best_params_)

# Train the best model
best_model1 = grid_search.best_estimator_
y_train_pred = best_model1.predict(X_train)
y_test_pred = best_model1.predict(X_test)

# Evaluate the model
print("Train Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred))
print("Test Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print("Train Classification Report:\n", classification_report(y_train, y_train_pred))
print("Test Classification Report:\n", classification_report(y_test, y_test_pred))


Best parameters: {'algorithm': 'SAMME.R', 'learning_rate': 0.1, 'n_estimators': 200}
Train Confusion Matrix:
 [[320 103]
 [ 35 359]]
Test Confusion Matrix:
 [[74 21]
 [16 94]]
Train Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.76      0.82       423
           1       0.78      0.91      0.84       394

    accuracy                           0.83       817
   macro avg       0.84      0.83      0.83       817
weighted avg       0.84      0.83      0.83       817

Test Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.78      0.80        95
           1       0.82      0.85      0.84       110

    accuracy                           0.82       205
   macro avg       0.82      0.82      0.82       205
weighted avg       0.82      0.82      0.82       205



In [69]:
from sklearn.naive_bayes import GaussianNB

model5= GaussianNB()
model5.fit(X_train,y_train)
y_train_pred=model5.predict(X_train)
y_test_pred=model5.predict(X_test)
print(confusion_matrix(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_train,y_train_pred))
print(classification_report(y_test,y_test_pred))

[[423   0]
 [393   1]]
[[ 95   0]
 [110   0]]
              precision    recall  f1-score   support

           0       0.52      1.00      0.68       423
           1       1.00      0.00      0.01       394

    accuracy                           0.52       817
   macro avg       0.76      0.50      0.34       817
weighted avg       0.75      0.52      0.36       817

              precision    recall  f1-score   support

           0       0.46      1.00      0.63        95
           1       0.00      0.00      0.00       110

    accuracy                           0.46       205
   macro avg       0.23      0.50      0.32       205
weighted avg       0.21      0.46      0.29       205



In [70]:
from sklearn.neighbors import KNeighborsClassifier

model6= KNeighborsClassifier()
model6.fit(X_train,y_train)
y_train_pred=model6.predict(X_train)
y_test_pred=model6.predict(X_test)
print(confusion_matrix(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_train,y_train_pred))
print(classification_report(y_test,y_test_pred))

[[365  58]
 [ 71 323]]
[[76 19]
 [37 73]]
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       423
           1       0.85      0.82      0.83       394

    accuracy                           0.84       817
   macro avg       0.84      0.84      0.84       817
weighted avg       0.84      0.84      0.84       817

              precision    recall  f1-score   support

           0       0.67      0.80      0.73        95
           1       0.79      0.66      0.72       110

    accuracy                           0.73       205
   macro avg       0.73      0.73      0.73       205
weighted avg       0.74      0.73      0.73       205



In [71]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Define the hyperparameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],  # Number of neighbors
    'weights': ['uniform', 'distance'],  # Weight function used in prediction
    'metric': ['euclidean', 'manhattan', 'minkowski']  # Distance metric
}

# Initialize the KNN classifier
model6 = KNeighborsClassifier()

# Perform Grid Search with cross-validation
grid_search = GridSearchCV(model6, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Best parameters and best model
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validation Score:", grid_search.best_score_)

# Train the best model
best_model2 = grid_search.best_estimator_

# Predictions
y_train_pred = best_model2.predict(X_train)
y_test_pred = best_model2.predict(X_test)

# Evaluation
print("Train Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred))
print("Test Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print("Train Classification Report:\n", classification_report(y_train, y_train_pred))
print("Test Classification Report:\n", classification_report(y_test, y_test_pred))


Best Parameters: {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'distance'}
Best Cross-Validation Score: 0.7564117911117763
Train Confusion Matrix:
 [[423   0]
 [  1 393]]
Test Confusion Matrix:
 [[74 21]
 [30 80]]
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       423
           1       1.00      1.00      1.00       394

    accuracy                           1.00       817
   macro avg       1.00      1.00      1.00       817
weighted avg       1.00      1.00      1.00       817

Test Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.78      0.74        95
           1       0.79      0.73      0.76       110

    accuracy                           0.75       205
   macro avg       0.75      0.75      0.75       205
weighted avg       0.75      0.75      0.75       205



In [72]:
from sklearn.svm import SVC
model7= SVC()
model7.fit(X_train,y_train)
y_train_pred=model7.predict(X_train)
y_test_pred=model7.predict(X_test)
print(confusion_matrix(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_train,y_train_pred))
print(classification_report(y_test,y_test_pred))

[[423   0]
 [393   1]]
[[ 95   0]
 [110   0]]
              precision    recall  f1-score   support

           0       0.52      1.00      0.68       423
           1       1.00      0.00      0.01       394

    accuracy                           0.52       817
   macro avg       0.76      0.50      0.34       817
weighted avg       0.75      0.52      0.36       817

              precision    recall  f1-score   support

           0       0.46      1.00      0.63        95
           1       0.00      0.00      0.00       110

    accuracy                           0.46       205
   macro avg       0.23      0.50      0.32       205
weighted avg       0.21      0.46      0.29       205



In [73]:
from sklearn.ensemble import GradientBoostingClassifier
model8 = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=2, random_state=42)
model8.fit(X_train, y_train)
y_train_pred=model8.predict(X_train)
y_test_pred=model8.predict(X_test)
print(confusion_matrix(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_train,y_train_pred))
print(classification_report(y_test,y_test_pred))

[[347  76]
 [ 40 354]]
[[76 19]
 [24 86]]
              precision    recall  f1-score   support

           0       0.90      0.82      0.86       423
           1       0.82      0.90      0.86       394

    accuracy                           0.86       817
   macro avg       0.86      0.86      0.86       817
weighted avg       0.86      0.86      0.86       817

              precision    recall  f1-score   support

           0       0.76      0.80      0.78        95
           1       0.82      0.78      0.80       110

    accuracy                           0.79       205
   macro avg       0.79      0.79      0.79       205
weighted avg       0.79      0.79      0.79       205



In [74]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Define parameter grid
param_grid = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [2, 3, 4]
}

# Initialize model
model = GradientBoostingClassifier(random_state=42)

# Perform Grid Search
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Print best parameters
print("Best Parameters:", grid_search.best_params_)

# Train the best model
best_model3 = grid_search.best_estimator_
best_model3.fit(X_train, y_train)

# Predictions
y_train_pred = best_model3.predict(X_train)
y_test_pred = best_model3.predict(X_test)

# Evaluation
print("Train Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred))
print("Test Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print("Train Classification Report:\n", classification_report(y_train, y_train_pred))
print("Test Classification Report:\n", classification_report(y_test, y_test_pred))


Best Parameters: {'learning_rate': 0.1, 'max_depth': 2, 'n_estimators': 50}
Train Confusion Matrix:
 [[336  87]
 [ 42 352]]
Test Confusion Matrix:
 [[77 18]
 [19 91]]
Train Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.79      0.84       423
           1       0.80      0.89      0.85       394

    accuracy                           0.84       817
   macro avg       0.85      0.84      0.84       817
weighted avg       0.85      0.84      0.84       817

Test Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.81      0.81        95
           1       0.83      0.83      0.83       110

    accuracy                           0.82       205
   macro avg       0.82      0.82      0.82       205
weighted avg       0.82      0.82      0.82       205



In [75]:
%pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [76]:
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report

# Initialize XGBoost model
model9 = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=2, random_state=42, use_label_encoder=False, eval_metric='logloss')

# Fit the model
model9.fit(X_train, y_train)

# Predictions
y_train_pred = model9.predict(X_train)
y_test_pred = model9.predict(X_test)

# Print confusion matrices
print(confusion_matrix(y_train, y_train_pred))
print(confusion_matrix(y_test, y_test_pred))

# Print classification reports
print(classification_report(y_train, y_train_pred))
print(classification_report(y_test, y_test_pred))


[[341  82]
 [ 43 351]]
[[77 18]
 [19 91]]
              precision    recall  f1-score   support

           0       0.89      0.81      0.85       423
           1       0.81      0.89      0.85       394

    accuracy                           0.85       817
   macro avg       0.85      0.85      0.85       817
weighted avg       0.85      0.85      0.85       817

              precision    recall  f1-score   support

           0       0.80      0.81      0.81        95
           1       0.83      0.83      0.83       110

    accuracy                           0.82       205
   macro avg       0.82      0.82      0.82       205
weighted avg       0.82      0.82      0.82       205



In [77]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Define the XGBoost model
xgb_model = XGBClassifier()

# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [2, 4, 6],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# Set up GridSearchCV
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, 
                           scoring='accuracy', cv=5, n_jobs=-1, verbose=1)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Get the best parameters and best estimator
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

print("Best Parameters:", best_params)

# Make predictions with the best model
y_train_pred = best_model.predict(X_train)
y_test_pred = best_model.predict(X_test)

# Print confusion matrices
print("Confusion Matrix - Train:\n", confusion_matrix(y_train, y_train_pred))
print("Confusion Matrix - Test:\n", confusion_matrix(y_test, y_test_pred))

# Print classification reports
print("Classification Report - Train:\n", classification_report(y_train, y_train_pred))
print("Classification Report - Test:\n", classification_report(y_test, y_test_pred))


Fitting 5 folds for each of 108 candidates, totalling 540 fits
Best Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 2, 'n_estimators': 50, 'subsample': 1.0}
Confusion Matrix - Train:
 [[330  93]
 [ 41 353]]
Confusion Matrix - Test:
 [[76 19]
 [18 92]]
Classification Report - Train:
               precision    recall  f1-score   support

           0       0.89      0.78      0.83       423
           1       0.79      0.90      0.84       394

    accuracy                           0.84       817
   macro avg       0.84      0.84      0.84       817
weighted avg       0.84      0.84      0.84       817

Classification Report - Test:
               precision    recall  f1-score   support

           0       0.81      0.80      0.80        95
           1       0.83      0.84      0.83       110

    accuracy                           0.82       205
   macro avg       0.82      0.82      0.82       205
weighted avg       0.82      0.82      0.82       205



In [78]:
test

S.No         Timestamp  Age  Gender         Country state self_employed  \
0       1   8/29/2014 11:32   39    Male  United Kingdom   NaN           Yes   
1       2   8/29/2014 11:32   26  female   United States    WA            No   
2       3   8/29/2014 11:33   23  Female   United States    IL            No   
3       4   8/29/2014 11:34   35    Male     Switzerland   NaN            No   
4       5   8/29/2014 11:36   36    Male   United States    FL            No   
..    ...               ...  ...     ...             ...   ...           ...   
205   206   9/12/2015 11:17   26    male  United Kingdom   NaN            No   
206   207    9/26/2015 1:07   32    Male   United States    IL            No   
207   208   11/7/2015 12:36   34    male   United States    CA            No   
208   209  11/30/2015 21:25   46       f   United States    NC            No   
209   210    2/1/2016 23:04   25    Male   United States    IL            No   

    family_history work_interfere    no_employees remote_work tech_company  \
0              Yes      Sometimes           5-Jan         Yes          Yes   
1              Yes      Sometimes  More than 1000          No          Yes   
2              Yes      Sometimes          26-100          No           No   
3              Yes          Often  More than 1000          No          Yes   
4               No          Never           5-Jan         Yes          Yes   
..             ...            ...             ...         ...          ...   
205             No            NaN          26-100          No          Yes   
206            Yes          Often          26-100         Yes          Yes   
207            Yes      Sometimes  More than 1000          No          Yes   
208             No            NaN         100-500         Yes          Yes   
209            Yes      Sometimes          26-100          No           No   

       benefits care_options wellness_program   seek_help   anonymity  \
0            No          Yes              Yes         Yes         Yes   
1           Yes          Yes               No          No  Don't know   
2            No           No               No          No  Don't know   
3    Don't know     Not sure               No          No         Yes   
4    Don't know     Not sure       Don't know  Don't know  Don't know   
..          ...          ...              ...         ...         ...   
205          No           No               No          No  Don't know   
206         Yes          Yes               No          No         Yes   
207         Yes          Yes               No          No  Don't know   
208          No          Yes               No          No  Don't know   
209         Yes          Yes               No          No         Yes   

                  leave mental_health_consequence phys_health_consequence  \
0    Somewhat difficult                        No                      No   
1            Don't know                        No                      No   
2    Somewhat difficult                       Yes                      No   
3             Very easy                        No                      No   
4             Very easy                        No                      No   
..                  ...                       ...                     ...   
205       Somewhat easy                        No                      No   
206  Somewhat difficult                        No                      No   
207  Somewhat difficult                       Yes                     Yes   
208          Don't know                       Yes                      No   
209          Don't know                     Maybe                      No   

        coworkers    supervisor mental_health_interview phys_health_interview  \
0             Yes           Yes                      No                 Maybe   
1    Some of them           Yes                      No                 Maybe   
2              No  Some of them                      No       

## Test

In [80]:
test.drop(columns = 'S.No',inplace=True)

In [81]:
test.drop(columns = 'Timestamp',inplace=True)

In [82]:
test.drop(columns = 'Gender',inplace=True)

In [83]:
test.drop(columns = 'Country',inplace=True)

In [84]:
test.drop(columns = 'state',inplace=True)

In [85]:
test.drop(columns = 'self_employed',inplace=True)

In [86]:
test.drop(columns = 'remote_work',inplace=True)

In [87]:
test.drop(columns = 'tech_company',inplace=True)

In [88]:
test.drop(columns = 'coworkers',inplace=True)

In [89]:
test.drop(columns = 'mental_health_interview',inplace=True)

In [90]:
test.drop(columns = 'phys_health_interview',inplace=True)

In [91]:
test.drop(columns = 'mental_vs_physical',inplace=True)

In [92]:
test.drop(columns = 'obs_consequence',inplace=True)

In [93]:
test.drop(columns = 'comments',inplace=True)

In [94]:
test.work_interfere.replace({'Rarely':'Often','Sometimes':'Often'},inplace = True)

In [95]:
test.wellness_program.replace({"Don't know":'No'},inplace = True)

In [96]:
test.seek_help.replace({"Don't know":'No'},inplace = True)

In [97]:
test.leave.replace({'Somewhat easy':'Easy_Approval',"Don't know":'Easy_Approval','Very easy':'Easy_Approval','Somewhat difficult': 'Difficult_Approval','Very difficult':'Difficult_Approval'},inplace = True)

In [98]:
test.mental_health_consequence.replace({'Maybe':'Yes'},inplace = True)

In [99]:
test.phys_health_consequence .replace({'Maybe':'Yes'},inplace = True)

In [100]:
test.isnull().sum()

Age                           0
family_history                0
work_interfere               28
no_employees                  0
benefits                      3
care_options                  0
wellness_program              2
seek_help                     0
anonymity                     0
leave                         5
mental_health_consequence     0
phys_health_consequence       0
supervisor                    0
dtype: int64

In [101]:
test.work_interfere.fillna("Never",inplace=True)

In [102]:
test.benefits.fillna("Don't know",inplace=True)

In [103]:
test.wellness_program.fillna("No",inplace=True)

In [104]:
test.leave.fillna("Easy_Approval",inplace=True)

In [105]:
ftest = pd.get_dummies(test,drop_first = True).astype('int')

In [106]:
ftest

Age  family_history_Yes  work_interfere_Often  no_employees_25-Jun  \
0     39                   1                     1                    0   
1     26                   1                     1                    0   
2     23                   1                     1                    0   
3     35                   1                     1                    0   
4     36                   0                     0                    0   
..   ...                 ...                   ...                  ...   
205   26                   0                     0                    0   
206   32                   1                     1                    0   
207   34                   1                     1                    0   
208   46                   0                     0                    0   
209   25                   1                     1                    0   

     no_employees_26-100  no_employees_5-Jan  no_employees_500-1000  \
0                      0                   1                      0   
1                      0                   0                      0   
2                      1                   0                      0   
3                      0                   0                      0   
4                      0                   1                      0   
..                   ...                 ...                    ...   
205                    1                   0                      0   
206                    1                   0                      0   
207                    0                   0                      0   
208                    0                   0                      0   
209                    1                   0                      0   

     no_employees_More than 1000  benefits_No  benefits_Yes  \
0                              0            1             0   
1                              1            0             1   
2                              0            1             0   
3                              1            0             0   
4                              0            0             0   
..                           ...          ...           ...   
205                            0            1             0   
206                            0            0             1   
207                            1            0             1   
208                            0            1             0   
209                            0            0             1   

     care_options_Not sure  care_options_Yes  wellness_program_Yes  \
0                        0                 1                     1   
1                        0                 1                     0   
2                        0                 0                     0   
3                        1                 0                     0   
4                        1                 0                     0   
..                     ...               ...                   ...   
205                      0                 0                     0   
206                      0                 1                     0   
207                      0                 1                     0   
208                      0                 1                     0   
209                      0                 1                     0   

     seek_help_Yes  anonymity_No  anonymity_Yes  leave_Easy_Approval  \
0                1             0              1                    0   
1                0             0              0                    1   
2                0             0              0                    0   
3                0             0              1                    1   
4                0             0              0                    1   
..             ...           ...            ...                  ...   
205              0             0              0                    1   
206              0             0              1                    0   
207  

In [107]:
output = pd.DataFrame(best_model.predict(ftest))

ValueError: feature_names mismatch: ['Age', 'family_history_Yes', 'work_interfere_Often', 'no_employees_25-Jun', 'no_employees_26-100', 'no_employees_5-Jan', 'no_employees_500-1000', 'no_employees_More than 1000', 'benefits_No', 'benefits_Yes', 'care_options_Yes', 'wellness_program_Yes', 'seek_help_Yes', 'anonymity_No', 'anonymity_Yes', 'leave_Easy_Approval', 'mental_health_consequence_Yes', 'phys_health_consequence_Yes', 'supervisor_Some of them', 'supervisor_Yes'] ['Age', 'family_history_Yes', 'work_interfere_Often', 'no_employees_25-Jun', 'no_employees_26-100', 'no_employees_5-Jan', 'no_employees_500-1000', 'no_employees_More than 1000', 'benefits_No', 'benefits_Yes', 'care_options_Not sure', 'care_options_Yes', 'wellness_program_Yes', 'seek_help_Yes', 'anonymity_No', 'anonymity_Yes', 'leave_Easy_Approval', 'mental_health_consequence_Yes', 'phys_health_consequence_Yes', 'supervisor_Some of them', 'supervisor_Yes']
training data did not have the following fields: care_options_Not sure

In [ ]:
output.columns = ['Treatment']

In [ ]:
output.head()

In [ ]:
output.Treatment.replace({1:'Yes',0:'No'},inplace = True)

In [ ]:
output

In [ ]:
output.to_csv('final_submission35.csv',index = False)

In [108]:
ftrain1 = ftrain.copy(deep = True)

In [110]:
ftest1 = ftest.copy(deep = True)

In [113]:
import imblearn
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=0)
x_ros, y_ros = ros.fit_resample(X, y)

print('original dataset shape:', y.value_counts())
print('Resample dataset shape', y_ros.value_counts())

original dataset shape: treatment
0    518
1    504
Name: count, dtype: int64
Resample dataset shape treatment
1    518
0    518
Name: count, dtype: int64


In [114]:
X_ros_train,X_ros_test,y_ros_train,y_ros_test = train_test_split(x_ros,y_ros,test_size= 0.2, random_state=42)

In [116]:
mo = XGBClassifier()
mo.fit(X_ros_train,y_ros_train)
y_train_pred = mo.predict(X_ros_train)
y_test_pred = mo.predict(X_ros_test)
display(confusion_matrix(y_ros_train,y_train_pred))
confusion_matrix(y_ros_test,y_test_pred)
print(classification_report(y_ros_train,y_train_pred))
print(classification_report(y_ros_test,y_test_pred))

array([[418,   2],
       [  3, 405]], dtype=int64)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       420
           1       1.00      0.99      0.99       408

    accuracy                           0.99       828
   macro avg       0.99      0.99      0.99       828
weighted avg       0.99      0.99      0.99       828

              precision    recall  f1-score   support

           0       0.73      0.79      0.76        98
           1       0.80      0.75      0.77       110

    accuracy                           0.76       208
   macro avg       0.76      0.77      0.76       208
weighted avg       0.77      0.76      0.76       208



In [118]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Define the model
mo = XGBClassifier()

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 200],  # Number of trees
    'max_depth': [3, 5, 7],  # Maximum depth of trees
    'learning_rate': [0.01, 0.1, 0.2],  # Step size shrinkage
    'subsample': [0.7, 1],  # Fraction of samples for each tree
    'colsample_bytree': [0.7, 1]  # Fraction of features used for each tree
}

# Perform Grid Search with Cross-Validation
grid_search = GridSearchCV(mo, param_grid, cv=3, scoring='accuracy', n_jobs=-1, verbose=1)
grid_search.fit(X_ros_train, y_ros_train)

# Get the best model
best_model = grid_search.best_estimator_

# Predict on training data
y_train_pred = best_model.predict(X_ros_train)
y_test_pred = best_model.predict(X_ros_test)

# Display confusion matrix and classification report
print("Train Confusion Matrix:\n", confusion_matrix(y_ros_train, y_train_pred))
print("Test Confusion Matrix:\n", confusion_matrix(y_ros_test, y_test_pred))

print("\nTrain Classification Report:\n", classification_report(y_ros_train, y_train_pred))
print("\nTest Classification Report:\n", classification_report(y_ros_test, y_test_pred))

# Best parameters found by Grid Search
print("Best Hyperparameters:", grid_search.best_params_)


Fitting 3 folds for each of 108 candidates, totalling 324 fits
Train Confusion Matrix:
 [[342  78]
 [ 48 360]]
Test Confusion Matrix:
 [[78 20]
 [19 91]]

Train Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.81      0.84       420
           1       0.82      0.88      0.85       408

    accuracy                           0.85       828
   macro avg       0.85      0.85      0.85       828
weighted avg       0.85      0.85      0.85       828


Test Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.80      0.80        98
           1       0.82      0.83      0.82       110

    accuracy                           0.81       208
   macro avg       0.81      0.81      0.81       208
weighted avg       0.81      0.81      0.81       208

Best Hyperparameters: {'colsample_bytree': 0.7, 'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 200, 'subsample': 1}


In [121]:
import imblearn
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=0, replacement=True)
x_rus, y_rus = rus.fit_resample(X, y)

print('original dataset shape:', y.value_counts())
print('Resample dataset shape', y_rus.value_counts())

original dataset shape: treatment
0    518
1    504
Name: count, dtype: int64
Resample dataset shape treatment
0    504
1    504
Name: count, dtype: int64


In [122]:
X_rus_train,X_rus_test,y_rus_train,y_rus_test = train_test_split(x_rus,y_rus,test_size= 0.2, random_state=0)

In [123]:
mu = RandomForestClassifier()
mu.fit(X_rus_train,y_rus_train)

RandomForestClassifier()

In [124]:
y_train_pred = mu.predict(X_rus_train)
y_test_pred = mu.predict(X_rus_test)


In [125]:
display(confusion_matrix(y_rus_train,y_train_pred))
display(confusion_matrix(y_rus_test,y_test_pred))

array([[406,   0],
       [  1, 399]], dtype=int64)

array([[87, 11],
       [15, 89]], dtype=int64)

In [126]:
print(classification_report(y_rus_train,y_train_pred))
print(classification_report(y_rus_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       406
           1       1.00      1.00      1.00       400

    accuracy                           1.00       806
   macro avg       1.00      1.00      1.00       806
weighted avg       1.00      1.00      1.00       806

              precision    recall  f1-score   support

           0       0.85      0.89      0.87        98
           1       0.89      0.86      0.87       104

    accuracy                           0.87       202
   macro avg       0.87      0.87      0.87       202
weighted avg       0.87      0.87      0.87       202



In [128]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Define parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

# Initialize the model
rf = RandomForestClassifier(random_state=0)

# Perform Grid Search with cross-validation
grid_search = GridSearchCV(rf, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)
grid_search.fit(X_rus_train, y_rus_train)

# Best parameters and model
print("Best Parameters:", grid_search.best_params_)
best_rf = grid_search.best_estimator_

# Predictions
y_train_pred = best_rf.predict(X_rus_train)
y_test_pred = best_rf.predict(X_rus_test)

# Evaluate the model
print("Train Confusion Matrix:\n", confusion_matrix(y_rus_train, y_train_pred))
print("Test Confusion Matrix:\n", confusion_matrix(y_rus_test, y_test_pred))
print("Train Classification Report:\n", classification_report(y_rus_train, y_train_pred))
print("Test Classification Report:\n", classification_report(y_rus_test, y_test_pred))

Fitting 5 folds for each of 216 candidates, totalling 1080 fits
Best Parameters: {'bootstrap': False, 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 200}
Train Confusion Matrix:
 [[364  42]
 [ 12 388]]
Test Confusion Matrix:
 [[81 17]
 [14 90]]
Train Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.90      0.93       406
           1       0.90      0.97      0.93       400

    accuracy                           0.93       806
   macro avg       0.94      0.93      0.93       806
weighted avg       0.94      0.93      0.93       806

Test Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.83      0.84        98
           1       0.84      0.87      0.85       104

    accuracy                           0.85       202
   macro avg       0.85      0.85      0.85       202
weighted avg       0.85      0.85      0.85       202



In [132]:
output = pd.DataFrame(best_model.predict(ftest))

ValueError: feature_names mismatch: ['Age', 'family_history_Yes', 'work_interfere_Often', 'no_employees_25-Jun', 'no_employees_26-100', 'no_employees_5-Jan', 'no_employees_500-1000', 'no_employees_More than 1000', 'benefits_No', 'benefits_Yes', 'care_options_Yes', 'wellness_program_Yes', 'seek_help_Yes', 'anonymity_No', 'anonymity_Yes', 'leave_Easy_Approval', 'mental_health_consequence_Yes', 'phys_health_consequence_Yes', 'supervisor_Some of them', 'supervisor_Yes'] ['Age', 'family_history_Yes', 'work_interfere_Often', 'no_employees_25-Jun', 'no_employees_26-100', 'no_employees_5-Jan', 'no_employees_500-1000', 'no_employees_More than 1000', 'benefits_No', 'benefits_Yes', 'care_options_Not sure', 'care_options_Yes', 'wellness_program_Yes', 'seek_help_Yes', 'anonymity_No', 'anonymity_Yes', 'leave_Easy_Approval', 'mental_health_consequence_Yes', 'phys_health_consequence_Yes', 'supervisor_Some of them', 'supervisor_Yes']
training data did not have the following fields: care_options_Not sure

In [ ]:
output.columns = ['Treatment']

In [ ]:
output.head()

In [ ]:
output.Treatment.replace({1:'Yes',0:'No'},inplace = True)

In [ ]:
output.to_csv('final_submission36.csv',index = False)

In [160]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
x_smote, y_smote = smote.fit_resample(X, y)
print('Original dataset shape:', y.value_counts())
print('Resampled dataset shape after Tomek links:', y_smote.value_counts())

Original dataset shape: treatment
0    518
1    504
Name: count, dtype: int64
Resampled dataset shape after Tomek links: treatment
1    518
0    518
Name: count, dtype: int64


In [162]:
X_train_s,X_test_s,y_train_s,y_test_s = train_test_split(x_smote, y_smote,test_size=0.2,random_state=0)

In [163]:
# Train Logistic Regression
ms1 = LogisticRegression()
ms1.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms1.predict(X_train_s)
y_test_pred = ms1.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.78      0.83       410
           1       0.81      0.91      0.85       418

    accuracy                           0.84       828
   macro avg       0.85      0.84      0.84       828
weighted avg       0.85      0.84      0.84       828

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.77      0.83       108
           1       0.79      0.92      0.85       100

    accuracy                           0.84       208
   macro avg       0.85      0.84      0.84       208
weighted avg       0.85      0.84      0.84       208



In [165]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Define the model
ms1 = LogisticRegression()

# Define hyperparameter grid
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],  # Regularization strength
    'penalty': ['l1', 'l2', 'elasticnet', None],  # Regularization type
    'solver': ['liblinear', 'saga']  # Compatible solvers
}

# Perform Grid Search
grid_search = GridSearchCV(ms1, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=1)
grid_search.fit(X_train_s, y_train_s)

# Best parameters
print("Best Parameters:", grid_search.best_params_)

# Train the best model
msg1 = grid_search.best_estimator_
msg1.fit(X_train_s, y_train_s)

# Predict on the training and test set
y_train_pred = msg1.predict(X_train_s)
y_test_pred = msg1.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression with Best Parameters:")

print("Training Set Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Test Set Classification Report:\n", classification_report(y_test_s, y_test_pred))


Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best Parameters: {'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}
Logistic Regression with Best Parameters:
Training Set Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.71      0.80       410
           1       0.77      0.94      0.85       418

    accuracy                           0.83       828
   macro avg       0.85      0.83      0.82       828
weighted avg       0.85      0.83      0.82       828

Test Set Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.72      0.82       108
           1       0.76      0.96      0.85       100

    accuracy                           0.84       208
   macro avg       0.86      0.84      0.84       208
weighted avg       0.86      0.84      0.83       208



In [171]:
ms2 = DecisionTreeClassifier()
ms2.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms2.predict(X_train_s)
y_test_pred = ms2.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       410
           1       1.00      1.00      1.00       418

    accuracy                           1.00       828
   macro avg       1.00      1.00      1.00       828
weighted avg       1.00      1.00      1.00       828

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.73      0.75       108
           1       0.72      0.75      0.74       100

    accuracy                           0.74       208
   macro avg       0.74      0.74      0.74       208
weighted avg       0.74      0.74      0.74       208



In [173]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Define the parameter grid
param_grid = {
    'criterion': ['gini', 'entropy'],  # Splitting criteria
    'max_depth': [3, 5, 10, None],  # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],  # Minimum samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]  # Minimum samples required at a leaf node
}

# Initialize the DecisionTreeClassifier
ms2 = DecisionTreeClassifier()

# Perform Grid Search with Cross-Validation
grid_search = GridSearchCV(ms2, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_s, y_train_s)

# Get the best parameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Train the best model
msg2 = grid_search.best_estimator_

# Predictions on train and test sets
y_train_pred = msg2.predict(X_train_s)
y_test_pred = msg2.predict(X_test_s)

# Evaluate model performance
print("Decision Tree - Best Model Performance:")
print("Train Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Test Classification Report:\n", classification_report(y_test_s, y_test_pred))


Best Hyperparameters: {'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Decision Tree - Best Model Performance:
Train Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.71      0.80       410
           1       0.77      0.94      0.85       418

    accuracy                           0.83       828
   macro avg       0.85      0.83      0.82       828
weighted avg       0.85      0.83      0.82       828

Test Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.72      0.82       108
           1       0.76      0.96      0.85       100

    accuracy                           0.84       208
   macro avg       0.86      0.84      0.84       208
weighted avg       0.86      0.84      0.83       208



In [175]:
ms3 = RandomForestClassifier()
ms3.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms3.predict(X_train_s)
y_test_pred = ms3.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       410
           1       1.00      1.00      1.00       418

    accuracy                           1.00       828
   macro avg       1.00      1.00      1.00       828
weighted avg       1.00      1.00      1.00       828

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.81      0.83       108
           1       0.80      0.86      0.83       100

    accuracy                           0.83       208
   macro avg       0.83      0.83      0.83       208
weighted avg       0.83      0.83      0.83       208



In [177]:
ms33 = RandomForestClassifier(max_depth=10,min_samples_leaf=2,min_samples_split=5,random_state=42)  #for max_depth = 10 --- 90 and 84
ms33.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms33.predict(X_train_s)
y_test_pred = ms33.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.86      0.89       410
           1       0.87      0.94      0.90       418

    accuracy                           0.90       828
   macro avg       0.90      0.90      0.90       828
weighted avg       0.90      0.90      0.90       828

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.81      0.85       108
           1       0.81      0.90      0.85       100

    accuracy                           0.85       208
   macro avg       0.85      0.85      0.85       208
weighted avg       0.86      0.85      0.85       208



In [179]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Define the model
ms3 = RandomForestClassifier()

# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],  
    'max_depth': [None, 10, 20],  
    'min_samples_split': [2, 5, 10],  
    'min_samples_leaf': [1, 2, 4],  
    'criterion': ['gini', 'entropy']
}

# Perform Grid Search
grid_search = GridSearchCV(ms3, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=1)
grid_search.fit(X_train_s, y_train_s)

# Best parameters
print("Best Parameters:", grid_search.best_params_)

# Train model using the best parameters
msg3 = grid_search.best_estimator_

# Predict on training and test sets
y_train_pred = msg3.predict(X_train_s)
y_test_pred = msg3.predict(X_test_s)

# Evaluate the model
print("Random Forest Classification Report on Training Data:\n", classification_report(y_train_s, y_train_pred))
print("Random Forest Classification Report on Test Data:\n", classification_report(y_test_s, y_test_pred))


Fitting 5 folds for each of 162 candidates, totalling 810 fits
Best Parameters: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 50}
Random Forest Classification Report on Training Data:
               precision    recall  f1-score   support

           0       0.93      0.85      0.89       410
           1       0.86      0.94      0.90       418

    accuracy                           0.89       828
   macro avg       0.89      0.89      0.89       828
weighted avg       0.89      0.89      0.89       828

Random Forest Classification Report on Test Data:
               precision    recall  f1-score   support

           0       0.88      0.78      0.82       108
           1       0.79      0.88      0.83       100

    accuracy                           0.83       208
   macro avg       0.83      0.83      0.83       208
weighted avg       0.83      0.83      0.83       208



In [181]:
ms4 = AdaBoostClassifier()
ms4.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms4.predict(X_train_s)
y_test_pred = ms4.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.77      0.82       410
           1       0.80      0.89      0.84       418

    accuracy                           0.83       828
   macro avg       0.83      0.83      0.83       828
weighted avg       0.83      0.83      0.83       828

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.75      0.82       108
           1       0.77      0.91      0.83       100

    accuracy                           0.83       208
   macro avg       0.84      0.83      0.83       208
weighted avg       0.84      0.83      0.83       208



In [182]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Define AdaBoost model
ms4 = AdaBoostClassifier()

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],  # Number of weak learners
    'learning_rate': [0.01, 0.1, 1.0],  # Learning rate
    'algorithm': ['SAMME', 'SAMME.R']  # Algorithm type
}

# Perform Grid Search
grid_search = GridSearchCV(ms4, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_s, y_train_s)

# Get best parameters and best model
msg4 = grid_search.best_estimator_
print("Best Parameters:", grid_search.best_params_)

# Predictions with the best model
y_train_pred = msg4.predict(X_train_s)
y_test_pred = msg4.predict(X_test_s)

# Evaluate performance
print("AdaBoost Classification Report (Train):\n", classification_report(y_train_s, y_train_pred))
print("AdaBoost Classification Report (Test):\n", classification_report(y_test_s, y_test_pred))


Best Parameters: {'algorithm': 'SAMME.R', 'learning_rate': 0.1, 'n_estimators': 100}
AdaBoost Classification Report (Train):
               precision    recall  f1-score   support

           0       0.92      0.72      0.81       410
           1       0.78      0.94      0.85       418

    accuracy                           0.83       828
   macro avg       0.85      0.83      0.83       828
weighted avg       0.85      0.83      0.83       828

AdaBoost Classification Report (Test):
               precision    recall  f1-score   support

           0       0.95      0.71      0.81       108
           1       0.76      0.96      0.85       100

    accuracy                           0.83       208
   macro avg       0.85      0.84      0.83       208
weighted avg       0.86      0.83      0.83       208



In [185]:
ms5 = GaussianNB()
ms5.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms5.predict(X_train_s)
y_test_pred = ms5.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.50      1.00      0.66       410
           1       1.00      0.00      0.00       418

    accuracy                           0.50       828
   macro avg       0.75      0.50      0.33       828
weighted avg       0.75      0.50      0.33       828

Classification Report:
               precision    recall  f1-score   support

           0       0.52      1.00      0.68       108
           1       0.00      0.00      0.00       100

    accuracy                           0.52       208
   macro avg       0.26      0.50      0.34       208
weighted avg       0.27      0.52      0.35       208



In [187]:
ms6 = KNeighborsClassifier()
ms6.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms6.predict(X_train_s)
y_test_pred = ms6.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.85      0.84       410
           1       0.85      0.83      0.84       418

    accuracy                           0.84       828
   macro avg       0.84      0.84      0.84       828
weighted avg       0.84      0.84      0.84       828

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.82      0.81       108
           1       0.80      0.76      0.78       100

    accuracy                           0.79       208
   macro avg       0.79      0.79      0.79       208
weighted avg       0.79      0.79      0.79       208



In [189]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Define parameter grid for KNN
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],  # Different values of k
    'weights': ['uniform', 'distance'],  # Weight function
    'metric': ['euclidean', 'manhattan', 'minkowski']  # Distance metrics
}

# Initialize KNN classifier
knn = KNeighborsClassifier()

# Apply GridSearchCV
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_s, y_train_s)

# Best parameters and model
best_knn = grid_search.best_estimator_
print("Best Parameters:", grid_search.best_params_)

# Predict on train and test sets
y_train_pred = best_knn.predict(X_train_s)
y_test_pred = best_knn.predict(X_test_s)

# Evaluate performance
print("Classification Report (Train):\n", classification_report(y_train_s, y_train_pred))
print("Classification Report (Test):\n", classification_report(y_test_s, y_test_pred))


Best Parameters: {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'}
Classification Report (Train):
               precision    recall  f1-score   support

           0       0.80      0.83      0.82       410
           1       0.83      0.80      0.81       418

    accuracy                           0.81       828
   macro avg       0.81      0.81      0.81       828
weighted avg       0.81      0.81      0.81       828

Classification Report (Test):
               precision    recall  f1-score   support

           0       0.81      0.73      0.77       108
           1       0.74      0.81      0.77       100

    accuracy                           0.77       208
   macro avg       0.77      0.77      0.77       208
weighted avg       0.77      0.77      0.77       208



In [191]:
ms7 = SVC()
ms7.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms7.predict(X_train_s)
y_test_pred = ms7.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       410
           1       0.50      1.00      0.67       418

    accuracy                           0.50       828
   macro avg       0.25      0.50      0.34       828
weighted avg       0.25      0.50      0.34       828

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       108
           1       0.48      1.00      0.65       100

    accuracy                           0.48       208
   macro avg       0.24      0.50      0.32       208
weighted avg       0.23      0.48      0.31       208



In [193]:
ms8 = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=2, random_state=42)
ms8.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms8.predict(X_train_s)
y_test_pred = ms8.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.78      0.83       410
           1       0.81      0.90      0.85       418

    accuracy                           0.84       828
   macro avg       0.85      0.84      0.84       828
weighted avg       0.85      0.84      0.84       828

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.73      0.81       108
           1       0.76      0.93      0.84       100

    accuracy                           0.83       208
   macro avg       0.84      0.83      0.83       208
weighted avg       0.84      0.83      0.83       208



In [195]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Define the model
ms8 = GradientBoostingClassifier()

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of boosting stages
    'learning_rate': [0.01, 0.1, 0.2],  # Step size shrinkage
    'max_depth': [3, 4, 5],  # Maximum depth of individual estimators
    'subsample': [0.8, 1.0]  # Fraction of samples used for fitting individual trees
}

# Perform Grid Search with Cross-Validation
grid_search = GridSearchCV(ms8, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=1)
grid_search.fit(X_train_s, y_train_s)

# Get the best model
msg8 = grid_search.best_estimator_

# Predict on the training and test sets using the best model
y_train_pred = msg8.predict(X_train_s)
y_test_pred = msg8.predict(X_test_s)

# Print evaluation metrics
print("Best Parameters:", grid_search.best_params_)
print("\nClassification Report (Training Set):\n", classification_report(y_train_s, y_train_pred))
print("\nClassification Report (Test Set):\n", classification_report(y_test_s, y_test_pred))


Fitting 5 folds for each of 54 candidates, totalling 270 fits
Best Parameters: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 200, 'subsample': 1.0}

Classification Report (Training Set):
               precision    recall  f1-score   support

           0       0.92      0.71      0.80       410
           1       0.77      0.94      0.85       418

    accuracy                           0.83       828
   macro avg       0.85      0.83      0.82       828
weighted avg       0.85      0.83      0.82       828


Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.95      0.72      0.82       108
           1       0.76      0.96      0.85       100

    accuracy                           0.84       208
   macro avg       0.86      0.84      0.84       208
weighted avg       0.86      0.84      0.83       208



In [197]:
ms88 = GradientBoostingClassifier(random_state=42)
ms88.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms88.predict(X_train_s)
y_test_pred = ms88.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.83      0.86       410
           1       0.84      0.91      0.87       418

    accuracy                           0.87       828
   macro avg       0.87      0.87      0.87       828
weighted avg       0.87      0.87      0.87       828

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.75      0.81       108
           1       0.77      0.90      0.83       100

    accuracy                           0.82       208
   macro avg       0.83      0.82      0.82       208
weighted avg       0.83      0.82      0.82       208



In [199]:
ms9 = XGBClassifier()
ms9.fit(X_train_s, y_train_s)

# Predict on the original test set
y_train_pred = ms9.predict(X_train_s)
y_test_pred = ms9.predict(X_test_s)

# Evaluate Logistic Regression performance
print("Logistic Regression:")

print("Classification Report:\n", classification_report(y_train_s, y_train_pred))
print("Classification Report:\n", classification_report(y_test_s, y_test_pred))

Logistic Regression:
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       410
           1       1.00      0.99      1.00       418

    accuracy                           1.00       828
   macro avg       1.00      1.00      1.00       828
weighted avg       1.00      1.00      1.00       828

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.81      0.81       108
           1       0.79      0.81      0.80       100

    accuracy                           0.81       208
   macro avg       0.81      0.81      0.81       208
weighted avg       0.81      0.81      0.81       208



In [201]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

# Define the XGBClassifier
ms9 = XGBClassifier()

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0]
}

# Perform Grid Search
grid_search = GridSearchCV(estimator=ms9, param_grid=param_grid, 
                           scoring='accuracy', cv=5, verbose=1, n_jobs=-1)

# Fit Grid Search to the training data
grid_search.fit(X_train_s, y_train_s)

msg9 = grid_search.best_estimator_

# Make predictions using the best model
y_train_pred = msg9.predict(X_train_s)
y_test_pred = msg9.predict(X_test_s)

# Evaluate performance
print("Best Parameters:", grid_search.best_params_)
print("\nClassification Report (Train):\n", classification_report(y_train_s, y_train_pred))
print("\nClassification Report (Test):\n", classification_report(y_test_s, y_test_pred))


Fitting 5 folds for each of 54 candidates, totalling 270 fits
Best Parameters: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.8}

Classification Report (Train):
               precision    recall  f1-score   support

           0       0.92      0.71      0.80       410
           1       0.77      0.94      0.85       418

    accuracy                           0.83       828
   macro avg       0.85      0.83      0.82       828
weighted avg       0.85      0.83      0.82       828


Classification Report (Test):
               precision    recall  f1-score   support

           0       0.95      0.72      0.82       108
           1       0.76      0.96      0.85       100

    accuracy                           0.84       208
   macro avg       0.86      0.84      0.84       208
weighted avg       0.86      0.84      0.83       208



In [ ]:
output = pd.DataFrame(msg9.predict(ftest))
output.columns = ['Treatment']
print(output.head())
output.Treatment.replace({1:'Yes',0:'No'},inplace = True)
output.to_csv('final_submission47.csv',index = False)